services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
      - 8000:8000 # Remove if you do not intend to use Edge Agents

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network


# Use this content for /srv/docker/stacks/portainer/docker-compose.yml

version: '3.8'

services:
  portainer:
    container_name: portainer
    # Using 'lts' tag is good practice for stability
    image: portainer/portainer-ce:lts 
    restart: always
    volumes:
      - /srv/docker/appdata/portainer/data:/data 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
      - 8000:8000 

networks:
  default:
    name: portainer_network
  environment:
      AGENT_CLUSTER_ADDR: ""
      AGENT_SSL: "false"



services:
  minio:

    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    command: server /data --console-address :9001
    restart: unless-stopped
    user: "1000:1000"

    environment:
      MINIO_ROOT_USER: proxima
      MINIO_ROOT_PASSWORD: @Edith2705#
    volumes:
      - /srv/docker/appdata/minio/data:/data
      - /srv/docker/appdata/minio/config:/root/.minio

    ports:
      - "9000:9000" 
      - "9001:9001" 

    networks:
      - core_net

networks:
  core_net:
    external: true




services:
  postgres:

    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: proxima
      POSTGRES_PASSWORD: "@Edith2705#"
      POSTGRES_DB: proximadatabase

    volumes:
      - /srv/docker/appdata/postgresql/data:/var/lib/postgresql

    ports:
      - "5432:5432"

    networks:
      - core_net

networks:
  core_net:
    external: true




services:
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      # Access via http://[Your Server IP]:8080
      - "8080:8080"
    networks:
      - core_net

networks:
  core_net:
    external: true



services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      # Access via http://[Your Server IP]:8989
      - "8989:8989"
    volumes:
      # Persistent storage for settings, drivers, and user configurations
      - /srv/docker/appdata/cloudbeaver/workspace:/opt/cloudbeaver/workspace
    networks:
      - core_net

networks:
  core_net:
    external: true




services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: "@Edith2705#" 
      MARIADB_USER: proxima
      MARIADB_PASSWORD: "@Edith2705#"
      MARIADB_DATABASE: appdatabase

    volumes:
      - /srv/docker/appdata/mariadb/data:/var/lib/mysql

    ports:
      - "3306:3306"

    networks:
      - core_net

networks:
  core_net:
    external: true




services:
  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass "@Edith2705#" 
    volumes:
      - /srv/docker/appdata/redis/data:/data 
    networks:
      - core_net

networks:
  core_net:
    external: true
